# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{simple_importer}
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Justin Marney"]
  s.date = %q{2009-10-22}
  s.description = %q{Provides a simple dsl for creating csv import tasks.}
  s.email = %q{gotascii@gmail.com}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    ".gitignore",
     "LICENSE",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "data/example.csv",
     "importers/example.rb",
     "lib/simple_importer.rb",
     "lib/simple_importer/tasks.rb",
     "lib/simple_importer/tasks/simple_importer.rake",
     "simple_importer.gemspec",
     "test/test_helper.rb",
     "test/test_simple_importer.rb"
  ]
  s.homepage = %q{http://github.com/vigetlabs/simple_importer}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{Simple api for importing from csv.}
  s.test_files = [
    "test/test_helper.rb",
     "test/test_simple_importer.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

